<?php
$this->inlineScript()->appendFile( $this->basePath( 'js/jquery-3.1.0.min.js' ) );
$this->inlineScript()->appendFile( $this->basePath( 'js/converter.js' ) );
?>
<div class="jumbotron">
    <h1>Currency Converter</h1>
</div>

<div class="row">

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Converter</h3>
            </div>
            <div class="panel-body">
                <form>
                    <div class="form-group">
                        <div class="input-group">
                            <input class="form-control" type="text" name="source" id="currency_source" placeholder="RUB"/>
                            <div class="input-group-addon">RUB</div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input class="form-control" name="target" id="currency_target" placeholder="PLN"
                                   disabled="disabled"/>
                            <div class="input-group-addon">PLN</div>
                        </div>
                    </div>
                    <p><a class="btn btn-success pull-right" id="convert_action" href="#" target="_blank">Convert</a></p>
                </form>
            </div>


        </div>
    </div>
</div>



